" Plugin management (vim-plug)
call plug#begin('~/.vim/plugged')
Plug 'dracula/vim', { 'as': 'dracula' }
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
call plug#end()

" Appearance
colorscheme dracula
syntax on
set number
set cursorline
set colorcolumn=88,120

" Filetype-specific settings
autocmd FileType python setlocal colorcolumn=88
autocmd FileType gitcommit setlocal colorcolumn=72

" Indentation
set autoindent
set smartindent
set expandtab
set tabstop=2
set shiftwidth=2
filetype plugin indent on

" Clipboard
set clipboard=unnamed

" Mouse
set mouse=a

" Undo
set undofile

" FZF mappings
nnoremap <leader>f :Files<cr>
nnoremap <leader>g :Rg<cr>
nnoremap <leader>b :Buffers<cr>
nnoremap <leader>h :History<cr>
nnoremap <leader>/ :BLines<cr>
